# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ivar's ranting
# email: blog@flurdy.tldreplcewithdotemail
copyright_year: 2019
copyright_name: Ivar Abrahamsen
author-name: Ivar Abrahamsen
author-nickname: Flurdy
author-jobtitle: Software Engineer
author-location: Hampshire, United Kingdom
author-avatar: me/stash2.jpg
author-avatar1: me/oculus.jpg
author-avatar2: me/ivarslips.jpg
author-avatar3: me/skina.jpg
author-description: >-
  <ul>
    <li>Developer then Tech Lead then Architect then Manager, now Consultant/Contractor.</li>
    <li>With Java then Scala and then a little Rust. And everything in between.</li>
    <li>From racks to AWS to Kubernetes.</li>
    <li>From waterfall to Scrum to Kanban to Lean to whatever works.</li>
    <li>From multinational enterprises to unicorn startups.</li>
    <li>From Telecoms to Finance to Game Studios to Media and back.</li>
    <li>Still is an Open Source wannabee hacker at night.</li>
  </ul>
author-description1: >-
  <p>
    Most of the blog posts are about technology and some about sport.
    All posts are very biased, based on little facts, unfiltered, non-pc,
    and eventually outdated...
  </p>
author-description2: >-
  <ul>
    <li>Hire me: <a href="https://eray.uk">eray.uk</a></li>
    <li>My website: <a href="https://flurdy.com">flurdy.com</a></li>
    <li>My ideas: <a href="https://code.flurdy.com">code.flurdy.com</a></li>
    <li>Who am I: <a href="https://ivar.uk/whoami.html">ivar.uk/whoami.html</a></li>
  </ul>
author-description3: >-
  <p>
    Ps. I rant a lot more on <a href="https://twitter.com/flurdy">Twitter</a> than I blog.
  </p>
description: >- # this means to ignore newlines until "baseurl:"
  The ramblings of Ivar Abrahamsen at flurdy.com.
  Contain ideas, ranting at innocents, blinkered sporting opinions,
  tech bable, and probably not enough to be interesting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.flurdy.com" # the base hostname & protocol for your site, e.g. http://example.com

twitter: https://twitter.com/flurdy
github: https://github.com/flurdy
facebook: https://facebook.com/flurdy
linkedin: https://linkedin.com/in/flurdy
keybase: https://keybase.io/flurdy
twitter_username: flurdy
github_username: flurdy
facebook_username: flurdy
linkedin_username: flurdy
keybase_username: flurdy
contact: https://ivar.uk/contact
website-url: https://flurdy.com
website-pretty: flurdy.com


rss: true

google-analytics: UA-281408-9

# Build settings
markdown: kramdown
permalink: '/:year/:month/:title:output_ext'
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives


paginate: 13
paginate_path: "/page/:num"

jekyll-archives:
  enabled:
    - year
    - month
    - tags
  layouts:
    year: archive-year
    month: archive-month
    tag: archive-tags

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - _imports
  - docker-compose.yml
  - Dockerfile
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - kube
