# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Flurdy's blog - Ivar's rambling
# email: blog@flurdy.tldreplcewithdotemail
author-name: Ivar Abrahamsen
author-avatar: ivarvr.jpg

description: >- # this means to ignore newlines until "baseurl:"
  The ramblings of Ivar Abrahamsen at flurdy.com.
  Contain ideas, ranting at innocents, blinkered sporting opinions,
  tech bable, and probably not enough to be interesting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.flurdy.com" # the base hostname & protocol for your site, e.g. http://example.com

twitter: https://twitter.com/flurdy
twitter_username: flurdy
github: https://github.com/flurdy
github_username:  flurdy
facebook: https://facebook.com/flurdy
facebook_username:  flurdy
linkedin: https://linkedin.com/in/flurdy
linkedin_username:  flurdy

# google-analytics: UA-281408-9

# Build settings
markdown: kramdown
# theme: minima
# theme: jekyll-theme-hydejack
# permalink: ':title/'
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives

paginate: 11
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
