version: '3'

services:
  jekyll:
    image: jekyll/jekyll:4.1.0
    container_name: blog
    environment:
      - JEKYLL_ENV=docker
    command: jekyll serve --force_polling --livereload --drafts
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - ./:/srv/jekyll
